name: VSTest Reusable Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      test-assembly:
        required: true
        type: string
      test-filter-criteria:
        required: false
        type: string
      configuration:
        required: true
        type: string
      platform:
        required: false
        type: string
      run-settings-file:
        required: false
        type: string
      code-coverage-enabled:
        required: false
        type: boolean
      test-run-title:
        required: false
        type: string

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration ${{ inputs.configuration }} --no-restore

      - name: Run tests
        run: |
          dotnet test `
            --configuration ${{ inputs.configuration }} `
            --logger "trx" `
            --results-directory TestResults `
            --collect:"XPlat Code Coverage" `
            --filter "${{ inputs.test-filter-criteria }}" `
            --settings "${{ inputs.run-settings-file }}"
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
