name: VSTest Reusable Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      test-assembly:
        required: true
        type: string
      test-filter-criteria:
        required: false
        type: string
      configuration:
        required: true
        type: string
      platform:
        required: false
        type: string
      code-coverage-enabled:
        required: false
        type: boolean
      test-run-title:
        required: false
        type: string
      custom-test-adapters:
        required: false
        type: string
      run-in-parallel:
        required: false
        type: boolean
      testPlan:
        required: false
        type: string
      testSuite:
        required: false
        type: string
      testConfiguration:
        required: false
        type: string
      tcmTestRun:
        required: false
        type: string
      sensitive-alphanumeric-info-1:
        required: false
        type: boolean
      sensitive-alphanumeric-info-2:
        required: false
        type: string
      uiTests:
        required: false
        type: boolean
      sensitive-alphanumeric-info-3:
        required: false
        type: string
      vsTestVersion:
        required: false
        type: string
      vstestLocation:
        required: false
        type: string
      sensitive-alphanumeric-info-4:
        required: false
        type: string
      otherConsoleOptions:
        required: false
        type: string
      diagnosticsEnabled:
        required: false
        type: boolean
      collectDumpOn:
        required: false
        type: string
      rerunFailedTests:
        required: false
        type: boolean
      rerunType:
        required: false
        type: string
      sensitive-alphanumeric-info-5:
        required: false
        type: string
      sensitive-alphanumeric-info-6:
        required: false
        type: string
      rerunMaxAttempts:
        required: false
        type: string
      sensitive-alphanumeric-info-7:
        required: false
        type: string
      sensitive-alphanumeric-info-8:
        required: false
        type: string
      sensitive-alphanumeric-info-9:
        required: false
        type: string
      sensitive-alphanumeric-info-10:
        required: false
        type: string
      sensitive-alphanumeric-info-11:
        required: false
        type: string
      dontDistribute:
        required: false
        type: boolean
      sensitive-alphanumeric-info-12:
        required: false
        type: boolean
      sensitive-alphanumeric-info-13:
        required: false
        type: boolean
      sensitive-alphanumeric-info-14:
        required: false
        type: boolean
      sensitive-alphanumeric-info-15:
        required: false
        type: string

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration ${{ inputs.configuration }} --no-restore

      - name: Run tests
        run: |
          dotnet test `
            --configuration ${{ inputs.configuration }} `
            --logger "trx" `
            --results-directory TestResults `
            ${ inputs.code-coverage-enabled && '--collect:"XPlat Code Coverage"' '' } `
            ${ inputs.test-filter-criteria && '--filter "${{ inputs.test-filter-criteria }}"' '' } `
            ${ inputs.custom-test-adapters && '-- TestAdapterPath="${{ inputs.custom-test-adapters }}"' '' } `
            ${ inputs.run-in-parallel && '--parallel' '' } `
            ${ inputs.diagnosticsEnabled && '--diag:logfile.txt' '' }
