name: Reusable VS Test Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      vsTestVersion:
        required: true
        type: string
      testAssembly:
        required: true
        type: string
      testFilterCriteria:
        required: false
        type: string
      runSettingsFile:
        required: false
        type: string
      codeCoverageEnabled:
        required: false
        type: boolean
      pathToCustomTestAdapters:
        required: false
        type: string
      overrideTestRunParameters:
        required: false
        type: string
      publishRunAttachments:
        required: false
        type: boolean
      runInParallel:
        required: false
        type: boolean
      testRunTitle:
        required: false
        type: string
      platform:
        required: false
        type: string
      configuration:
        required: false
        type: string
      otherConsoleOptions:
        required: false
        type: string

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration ${{ inputs.configuration }} --no-restore

      - name: Run Tests
        run: |
          dotnet test `
            --filter "${{ inputs.testFilterCriteria }}" `
            --settings "${{ inputs.runSettingsFile }}" `
            --logger trx `
            --configuration ${{ inputs.configuration }} `
            --collect:"XPlat Code Coverage" `
            ${{ inputs.otherConsoleOptions }}
