name: VSTest Reusable Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      test-assembly:
        required: true
        type: string
      test-filter-criteria:
        required: false
        type: string
      platform:
        required: false
        type: string
      code-coverage-enabled:
        required: false
        type: boolean
      custom-test-adapters:
        required: false
        type: string
      run-in-parallel:
        required: false
        type: boolean
      testPlan:
        required: false
        type: string
      testSuite:
        required: false
        type: string
      testConfiguration:
        required: false
        type: string
      tcmTestRun:
        required: false
        type: string
      uiTests:
        required: false
        type: boolean
      vstestLocationMethod:
        required: false
        type: string
      vsTestVersion:
        required: false
        type: string
      vstestLocation:
        required: false
        type: string
      overrideTestrunParameters:
        required: false
        type: string
      otherConsoleOptions:
        required: false
        type: string
      diagnosticsEnabled:
        required: false
        type: boolean
      collectDumpOn:
        required: false
        type: string
      rerunFailedTests:
        required: false
        type: boolean
      rerunType:
        required: false
        type: string
      rerunFailedThreshold:
        required: false
        type: string
      rerunFailedTestCasesMaxLimit:
        required: false
        type: string
      rerunMaxAttempts:
        required: false
        type: string
      distributionBatchType:
        required: false
        type: string
      batchingBasedOnAgentsOption:
        required: false
        type: string
      customBatchSizeValue:
        required: false
        type: string
      batchingBasedOnExecutionTimeOption:
        required: false
        type: string
      customRunTimePerBatchValue:
        required: false
        type: string
      dontDistribute:
        required: false
        type: boolean
      publishRunAttachments:
        required: false
        type: boolean
      donotPublishTestResults:
        required: false
        type: boolean
      failOnMinTestsNotRun:
        required: false
        type: boolean
      minimumExpectedTests:
        required: false
        type: string

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests
        run: |
          dotnet test `
            --logger "trx" `
            --results-directory "TestResults" `
            ${{ inputs.code-coverage-enabled && '--collect:"XPlat Code Coverage"' || '' }} `
            ${{ inputs.test-filter-criteria && format('--filter "{0}"', inputs.test-filter-criteria) || '' }} `
            ${{ inputs.custom-test-adapters && format('--TestAdapterPath "{0}"', inputs.custom-test-adapters) || '' }} `
            ${{ inputs.run-in-parallel && '--parallel' || '' }} `
            ${{ inputs.uiTests && '--uiTests' || '' }} `
            ${{ inputs.vstestLocationMethod && format('--vstestLocationMethod "{0}"', inputs.vstestLocationMethod) || '' }} `
            ${{ inputs.vsTestVersion && format('--vsTestVersion "{0}"', inputs.vsTestVersion) || '' }} `
            ${{ inputs.vstestLocation && format('--vstestLocation "{0}"', inputs.vstestLocation) || '' }} `
            ${{ inputs.overrideTestrunParameters && format('--overrideTestrunParameters "{0}"', inputs.overrideTestrunParameters) || '' }} `
            ${{ inputs.otherConsoleOptions || '' }} `
            ${{ inputs.diagnosticsEnabled && '--diagnosticsEnabled' || '' }} `
            ${{ inputs.collectDumpOn && format('--collectDumpOn "{0}"', inputs.collectDumpOn) || '' }} `
            ${{ inputs.rerunFailedTests && '--rerunFailedTests' || '' }} `
            ${{ inputs.rerunType && format('--rerunType "{0}"', inputs.rerunType) || '' }} `
            ${{ inputs.rerunFailedThreshold && format('--rerunFailedThreshold "{0}"', inputs.rerunFailedThreshold) || '' }} `
            ${{ inputs.rerunFailedTestCasesMaxLimit && format('--rerunFailedTestCasesMaxLimit "{0}"', inputs.rerunFailedTestCasesMaxLimit) || '' }} `
            ${{ inputs.rerunMaxAttempts && format('--rerunMaxAttempts "{0}"', inputs.rerunMaxAttempts) || '' }} `
            ${{ inputs.distributionBatchType && format('--distributionBatchType "{0}"', inputs.distributionBatchType) || '' }} `
            ${{ inputs.batchingBasedOnAgentsOption && format('--batchingBasedOnAgentsOption "{0}"', inputs.batchingBasedOnAgentsOption) || '' }} `
            ${{ inputs.customBatchSizeValue && format('--customBatchSizeValue "{0}"', inputs.customBatchSizeValue) || '' }} `
            ${{ inputs.batchingBasedOnExecutionTimeOption && format('--batchingBasedOnExecutionTimeOption "{0}"', inputs.batchingBasedOnExecutionTimeOption) || '' }} `
            ${{ inputs.customRunTimePerBatchValue && format('--customRunTimePerBatchValue "{0}"', inputs.customRunTimePerBatchValue) || '' }} `
            ${{ inputs.dontDistribute && '--dontDistribute' || '' }} `
            ${{ inputs.publishRunAttachments && '--publishRunAttachments' || '' }} `
            ${{ inputs.donotPublishTestResults && '--donotPublishTestResults' || '' }} `
            ${{ inputs.failOnMinTestsNotRun && '--failOnMinTestsNotRun' || '' }} `
            ${{ inputs.minimumExpectedTests && format('--minimumExpectedTests "{0}"', inputs.minimumExpectedTests) || '' }}
