name: Reusable .NET Test Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: "The version of .NET to use"
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Discover and Run Tests
        run: |
          testAssemblies=$(find . -type f -name "*Tests.dll")
          if [ -z "$testAssemblies" ]; then
            echo "No test assemblies found!"
            exit 1
          fi
          dotnet test --configuration Release --no-build --logger trx

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test-Results
          path: TestResults/*.trx
