name: VSTest Reusable Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      test-assembly:
        required: true
        type: string
      test-filter-criteria:
        required: false
        type: string
      configuration:
        required: true
        type: string
      platform:
        required: false
        type: string
      code-coverage-enabled:
        required: false
        type: boolean
      test-run-title:
        required: false
        type: string
      custom-test-adapters:
        required: false
        type: string
      run-in-parallel:
        required: false
        type: boolean
      testPlan:
        required: false
        type: string
      testSuite:
        required: false
        type: string
      testConfiguration:
        required: false
        type: string
      tcmTestRun:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_1:
        required: false
        type: boolean
      Sensitive_Alphanumeric_Info_2:
        required: false
        type: string
      uiTests:
        required: false
        type: boolean
      Sensitive_Alphanumeric_Info_3:
        required: false
        type: string
      vsTestVersion:
        required: false
        type: string
      vstestLocation:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_4:
        required: false
        type: string
      otherConsoleOptions:
        required: false
        type: string
      diagnosticsEnabled:
        required: false
        type: boolean
      collectDumpOn:
        required: false
        type: string
      rerunFailedTests:
        required: false
        type: boolean
      rerunType:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_5:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_6:
        required: false
        type: string
      rerunMaxAttempts:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_7:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_8:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_9:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_10:
        required: false
        type: string
      Sensitive_Alphanumeric_Info_11:
        required: false
        type: string
      dontDistribute:
        required: false
        type: boolean
      Sensitive_Alphanumeric_Info_12:
        required: false
        type: boolean
      Sensitive_Alphanumeric_Info_13:
        required: false
        type: boolean
      Sensitive_Alphanumeric_Info_14:
        required: false
        type: boolean
      Sensitive_Alphanumeric_Info_15:
        required: false
        type: string

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration ${{ inputs.configuration }} --no-restore

      - name: Run tests
        run: |
          dotnet test `
            --configuration "${{ inputs.configuration }}" `
            --logger "trx" `
            --results-directory "TestResults" `
            ${{ inputs.code-coverage-enabled && '--collect:"XPlat Code Coverage"' '' }} `
            ${{ inputs.test-filter-criteria && format('--filter "{0}"', inputs.test-filter-criteria) '' }} `
            ${{ inputs.custom-test-adapters && format('--TestAdapterPath "{0}"', inputs.custom-test-adapters) '' }} `
            ${{ inputs.run-in-parallel && '--parallel' '' }} `
            ${{ inputs.test-run-title && format('--testRunTitle "{0}"', inputs.test-run-title) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_1 && '-- Sensitive_Alphanumeric_Info_1' '' }} `
            ${{ inputs.uiTests && '--uiTests' '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_3 && format('-- Sensitive_Alphanumeric_Info_3 "{0}"', inputs. Sensitive_Alphanumeric_Info_3) '' }} `
            ${{ inputs.vsTestVersion && format('--vsTestVersion "{0}"', inputs.vsTestVersion) '' }} `
            ${{ inputs.vstestLocation && format('--vstestLocation "{0}"', inputs.vstestLocation) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_4 && format('-- Sensitive_Alphanumeric_Info_4 "{0}"', inputs. Sensitive_Alphanumeric_Info_4) '' }} `
            ${{ inputs.otherConsoleOptions '' }} `
            ${{ inputs.diagnosticsEnabled && '--diagnosticsEnabled' '' }} `
            ${{ inputs.collectDumpOn && format('--collectDumpOn "{0}"', inputs.collectDumpOn) '' }} `
            ${{ inputs.rerunFailedTests && '--rerunFailedTests' '' }} `
            ${{ inputs.rerunType && format('--rerunType "{0}"', inputs.rerunType) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_5 && format('-- Sensitive_Alphanumeric_Info_5 "{0}"', inputs. Sensitive_Alphanumeric_Info_5) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_6 && format('-- Sensitive_Alphanumeric_Info_6 "{0}"', inputs. Sensitive_Alphanumeric_Info_6) '' }} `
            ${{ inputs.rerunMaxAttempts && format('--rerunMaxAttempts "{0}"', inputs.rerunMaxAttempts) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_7 && format('-- Sensitive_Alphanumeric_Info_7 "{0}"', inputs. Sensitive_Alphanumeric_Info_7) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_8 && format('-- Sensitive_Alphanumeric_Info_8 "{0}"', inputs. Sensitive_Alphanumeric_Info_8) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_9 && format('-- Sensitive_Alphanumeric_Info_9 "{0}"', inputs. Sensitive_Alphanumeric_Info_9) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_10 && format('-- Sensitive_Alphanumeric_Info_10 "{0}"', inputs. Sensitive_Alphanumeric_Info_10) '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_11 && format('-- Sensitive_Alphanumeric_Info_11 "{0}"', inputs. Sensitive_Alphanumeric_Info_11) '' }} `
            ${{ inputs.dontDistribute && '--dontDistribute' '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_12 && '-- Sensitive_Alphanumeric_Info_12' '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_13 && '-- Sensitive_Alphanumeric_Info_13' '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_14 && '-- Sensitive_Alphanumeric_Info_14' '' }} `
            ${{ inputs. Sensitive_Alphanumeric_Info_15 && format('-- Sensitive_Alphanumeric_Info_15 "{0}"', inputs. Sensitive_Alphanumeric
