name: VStest Reusable Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      test-assembly:
        required: true
        type: string
      test-filter-criteria:
        required: true
        type: string
      run-settings-file:
        required: true
        type: string
      code-coverage-enabled:
        required: true
        type: boolean
      configuration:
        required: true
        type: string
      platform:
        required: true
        type: string
      test-run-title:
        required: true
        type: string
      custom-test-adapters:
        required: true
        type: string
      run-in-parallel:
        required: true
        type: boolean
      testPlan:
        required: true
        type: string
      testSuite:
        required: true
        type: string
      testConfiguration:
        required: true
        type: string
      tcmTestRun:
        required: true
        type: string
      sensitive-info-1:
        required: true
        type: string
      sensitive-info-11:
        required: true
        type: string
      sensitive-info-12:
        required: true
        type: string
      vsTestVersion:
        required: true
        type: string
      vstestLocation:
        required: true
        type: string
      sensitive-info-13:
        required: true
        type: string
      otherConsoleOptions:
        required: true
        type: string
      diagnosticsEnabled:
        required: true
        type: boolean
      collectDumpOn:
        required: true
        type: string
      rerunFailedTests:
        required: true
        type: boolean
      rerunType:
        required: true
        type: string
      sensitive-info-15:
        required: true
        type: string
      sensitive-info-16:
        required: true
        type: string
      rerunMaxAttempts:
        required: true
        type: string
      sensitive-info-17:
        required: true
        type: string
      sensitive-info-18:
        required: true
        type: string
      sensitive-info-1-0:
        required: true
        type: string
      sensitive-info-1-1:
        required: true
        type: string
      sensitive-info-1-2:
        required: true
        type: string
      dontDistribute:
        required: true
        type: boolean
      sensitive-info-1-3:
        required: true
        type: boolean
      sensitive-info-1-4:
        required: true
        type: boolean
      sensitive-info-1-5:
        required: true
        type: boolean
      sensitive-info-1-6:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Tests
        run: |
          dotnet test ^
            --configuration ${{ inputs.configuration }} ^
            --logger "trx" ^
            --results-directory TestResults ^
            --collect:"XPlat Code Coverage" ^
            --filter "${{ inputs.test-filter-criteria }}" ^
            --settings "${{ inputs.run-settings-file }}" ^
            -- TestAdapterPath="${{ inputs.custom-test-adapters }}" ^
            --blame ^
            --parallel=${{ inputs.run-in-parallel }} ^
            --diag:logfile.txt ^
            -- TestRunParameters.Parameter(name="TestPlan", value="${{ inputs.testPlan }}") ^
            -- TestRunParameters.Parameter(name="TestSuite", value="${{ inputs.testSuite }}") ^
            -- TestRunParameters.Parameter(name="TestConfiguration", value="${{ inputs.testConfiguration }}") ^
            -- TestRunParameters.Parameter(name="TcmTestRun", value="${{ inputs.tcmTestRun }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo1", value="${{ inputs.sensitive-info-1 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo11", value="${{ inputs.sensitive-info-11 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo12", value="${{ inputs.sensitive-info-12 }}") ^
            -- TestRunParameters.Parameter(name="vsTestVersion", value="${{ inputs.vsTestVersion }}") ^
            -- TestRunParameters.Parameter(name="vstestLocation", value="${{ inputs.vstestLocation }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo13", value="${{ inputs.sensitive-info-13 }}") ^
            -- TestRunParameters.Parameter(name="otherConsoleOptions", value="${{ inputs.otherConsoleOptions }}") ^
            -- TestRunParameters.Parameter(name="diagnosticsEnabled", value="${{ inputs.diagnosticsEnabled }}") ^
            -- TestRunParameters.Parameter(name="collectDumpOn", value="${{ inputs.collectDumpOn }}") ^
            -- TestRunParameters.Parameter(name="rerunFailedTests", value="${{ inputs.rerunFailedTests }}") ^
            -- TestRunParameters.Parameter(name="rerunType", value="${{ inputs.rerunType }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo15", value="${{ inputs.sensitive-info-15 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo16", value="${{ inputs.sensitive-info-16 }}") ^
            -- TestRunParameters.Parameter(name="rerunMaxAttempts", value="${{ inputs.rerunMaxAttempts }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo17", value="${{ inputs.sensitive-info-17 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo18", value="${{ inputs.sensitive-info-18 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo1-0", value="${{ inputs.sensitive-info-1-0 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo1-1", value="${{ inputs.sensitive-info-1-1 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo1-2", value="${{ inputs.sensitive-info-1-2 }}") ^
            -- TestRunParameters.Parameter(name="dontDistribute", value="${{ inputs.dontDistribute }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo1-3", value="${{ inputs.sensitive-info-1-3 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo1-4", value="${{ inputs.sensitive-info-1-4 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo1-5", value="${{ inputs.sensitive-info-1-5 }}") ^
            -- TestRunParameters.Parameter(name="SensitiveInfo1-6", value="${{ inputs.sensitive-info-1-6 }}")
