name: VSTest Reusable Workflow

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      test-assembly:
        required: true
        type: string
      test-filter-criteria:
        required: false
        type: string
      configuration:
        required: true
        type: string
      platform:
        required: false
        type: string
      run-settings-file:
        required: false
        type: string
      code-coverage-enabled:
        required: false
        type: boolean
      test-run-title:
        required: false
        type: string
      custom-test-adapters:
        required: false
        type: string
      run-in-parallel:
        required: false
        type: boolean
      testPlan:
        required: false
        type: string
      testSuite:
        required: false
        type: string
      testConfiguration:
        required: false
        type: string
      tcmTestRun:
        required: false
        type: string
      runOnlyImpactedTests:
        required: false
        type: boolean
      runAllTestsAfterXBuilds:
        required: false
        type: string
      uiTests:
        required: false
        type: boolean
      vstestLocationMethod:
        required: false
        type: string
      vsTestVersion:
        required: false
        type: string
      vstestLocation:
        required: false
        type: string
      overrideTestrunParameters:
        required: false
        type: string
      otherConsoleOptions:
        required: false
        type: string
      diagnosticsEnabled:
        required: false
        type: boolean
      collectDumpOn:
        required: false
        type: string
      rerunFailedTests:
        required: false
        type: boolean
      rerunType:
        required: false
        type: string
      rerunFailedThreshold:
        required: false
        type: string
      rerunFailedTestCasesMaxLimit:
        required: false
        type: string
      rerunMaxAttempts:
        required: false
        type: string
      distributionBatchType:
        required: false
        type: string
      batchingBasedOnAgentsOption:
        required: false
        type: string
      runOnlyImpactedTests0:
        required: false
        type: string
      runOnlyImpactedTests1:
        required: false
        type: string
      runOnlyImpactedTests2:
        required: false
        type: string
      dontDistribute:
        required: false
        type: boolean
      runOnlyImpactedTests3:
        required: false
        type: boolean
      runOnlyImpactedTests4:
        required: false
        type: boolean
      runOnlyImpactedTests5:
        required: false
        type: boolean
      runOnlyImpactedTests6:
        required: false
        type: string

jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration ${{ inputs.configuration }} --no-restore

      - name: Run tests
        run: |
          dotnet test `
            --configuration ${{ inputs.configuration }} `
            --logger "trx" `
            --results-directory TestResults `
            --collect:"XPlat Code Coverage" `
            --filter "${{ inputs.test-filter-criteria }}" `
            --settings "${{ inputs.run-settings-file }}" `
            -- TestAdapterPath="${{ inputs.custom-test-adapters }}" `
            --blame `
            --parallel=${{ inputs.run-in-parallel }} `
            --diag:logfile.txt `
            -- TestRunParameters.Parameter(name="TestPlan", value="${{ inputs.testPlan }}") `
            -- TestRunParameters.Parameter(name="TestSuite", value="${{ inputs.testSuite }}") `
            -- TestRunParameters.Parameter(name="TestConfiguration", value="${{ inputs.testConfiguration }}") `
            -- TestRunParameters.Parameter(name="TcmTestRun", value="${{ inputs.tcmTestRun }}") `
            -- TestRunParameters.Parameter(name="runOnlyImpactedTests", value="${{ inputs. runOnlyImpactedTests }}") `
            -- TestRunParameters.Parameter(name="runAllTestsAfterXBuilds", value="${{ inputs. runAllTestsAfterXBuilds }}") `
            -- TestRunParameters.Parameter(name="vstestLocationMethod", value="${{ inputs. vstestLocationMethod }}") `
            -- TestRunParameters.Parameter(name="vsTestVersion", value="${{ inputs.vsTestVersion }}") `
            -- TestRunParameters.Parameter(name="vstestLocation", value="${{ inputs.vstestLocation }}") `
            -- TestRunParameters.Parameter(name="overrideTestrunParameters", value="${{ inputs. overrideTestrunParameters }}") `
            -- TestRunParameters.Parameter(name="otherConsoleOptions", value="${{ inputs.otherConsoleOptions }}") `
            -- TestRunParameters.Parameter(name="diagnosticsEnabled", value="${{ inputs.diagnosticsEnabled }}") `
            -- TestRunParameters.Parameter(name="collectDumpOn", value="${{ inputs.collectDumpOn }}") `
            -- TestRunParameters.Parameter(name="rerunFailedTests", value="${{ inputs.rerunFailedTests }}") `
            -- TestRunParameters.Parameter(name="rerunType", value="${{ inputs.rerunType }}") `
            -- TestRunParameters.Parameter(name="rerunFailedThreshold", value="${{ inputs. rerunFailedThreshold }}") `
            -- TestRunParameters.Parameter(name="rerunFailedTestCasesMaxLimit", value="${{ inputs. rerunFailedTestCasesMaxLimit }}") `
            -- TestRunParameters.Parameter(name="rerunMaxAttempts", value="${{ inputs.rerunMaxAttempts }}") `
            -- TestRunParameters.Parameter(name="distributionBatchType", value="${{ inputs. distributionBatchType }}") `
            -- TestRunParameters.Parameter(name="batchingBasedOnAgentsOption", value="${{ inputs. batchingBasedOnAgentsOption }}") `
            -- TestRunParameters.Parameter(name="runOnlyImpactedTests0", value="${{ inputs. runOnlyImpactedTests0 }}") `
            -- TestRunParameters.Parameter(name="runOnlyImpactedTests1", value="${{ inputs. runOnlyImpactedTests1 }}") `
            -- TestRunParameters.Parameter(name="runOnlyImpactedTests2", value="${{ inputs. runOnlyImpactedTests2 }}") `
            -- TestRunParameters.Parameter(name="dontDistribute", value="${{ inputs.dontDistribute }}") `
            -- TestRunParameters.Parameter(name="runOnlyImpactedTests3", value="${{ inputs. runOnlyImpactedTests3 }}") `
            -- TestRunParameters.Parameter(name="runOnlyImpactedTests4", value="${{ inputs. runOnlyImpactedTests4 }}") `
            -- TestRunParameters.Parameter(name="runOnlyImpactedTests5", value="${{ inputs. runOnlyImpactedTests5 }}") `
            -- TestRunParameters.Parameter(name="runOnlyImpactedTests6", value="${{ inputs. runOnlyImpactedTests6 }}")
